const toString = val => (typeof val === 'string' ? val : '');
const identity = val => toString(val);

exports.abs = identity;
exports.append = identity;
exports.array_to_sentence_string = (array, connector = 'and') => {};
exports.as_liquid = item => {};
exports.asset_url = identity;
exports.assign = identity;
exports.capitalize = identity;
exports.ceil = identity;
exports.cgi_escape = input => {};
exports.compact = identity;
exports.customer_login_link = identity;
exports.customer_logout_link = identity;
exports.customer_register_link = identity;
exports.date = identity;
exports.decrement = identity;
exports.default = identity;
exports.default_errors = identity;
exports.default_pagination = identity;
exports.divided_by = identity;
exports.downcase = identity;
exports.else = identity;
exports.endraw = identity;
exports.escape = identity;
exports.escape_once = identity;
exports.first = identity;
exports.floor = identity;
exports.format_address = identity;
exports.get = identity;
exports.handle = identity;
exports.handleize = identity;
exports.highlight = identity;
exports.highlight_active = identity;
exports.img_tag = identity;
exports.img_url = identity;
exports.include = identity;
exports.increment = identity;
exports.inspect = input => {};
exports.item_property = (item, property) => {};
exports.join = identity;
exports.json = identity;
exports.jsonify = input => {};
exports.last = identity;
exports.link_to = identity;
exports.link_to_remove_tag = identity;
exports.link_to_tag = identity;
exports.link_to_vendor = identity;
exports.lstrip = identity;
exports.map = identity;
exports.markdownify = input => {};
exports.minus = identity;
exports.modulo = identity;
exports.money = identity;
exports.money_without_currency = identity;
exports.newline_to_br = identity;
exports.normalize_whitespace = input => {};
exports.number_of_words = input => {};
exports.parse_condition = exp => {};
exports.parse_sort_input = property => {};
exports.payment_type_img_url = identity;
exports.placeholder_svg_tag = identity;
exports.pluralize = identity;
exports.plus = identity;
exports.pop = (array, num = 1) => {};
exports.prepend = identity;
exports.Preview = identity;
exports.push = (array, input) => {};
exports.remove = identity;
exports.remove_first = identity;
exports.replace = identity;
exports.replace_first = identity;
exports.reverse = identity;
exports.round = identity;
exports.rstrip = identity;
exports.sample = (input, num = 1) => {};
exports.sassify = input => {};
exports.script_tag = identity;
exports.scssify = input => {};
exports.shift = (array, num = 1) => {};
exports.size = identity;
exports.slice = identity;
exports.slugify = (input, mode = null) => {};
exports.smartify = input => {};
exports.sort = (input, property = null, nils = 'first') => {};
exports.sort = identity;
exports.sort_input = (input, property, order) => {};
exports.sort_natural = identity;
exports.split = identity;
exports.strip = identity;
exports.strip_html = identity;
exports.strip_newlines = identity;
exports.stylesheet_tag = identity;
exports.time_tag = identity;
exports.times = identity;
exports.to_integer = input => {};
exports.truncate = identity;
exports.truncatewords = identity;
exports.uniq = identity;
exports.unshift = (array, input) => {};
exports.upcase = identity;
exports.uri_escape = input => {};
exports.url_decode = identity;
exports.url_encode = identity;
exports.weight_with_unit = identity;
exports.when = identity;
exports.where = (input, property, value) => {};
exports.where_exp = (input, variable, expression) => {};
exports.within = identity;
exports.xml_escape = input => {};
